#include <stdio.h>

int main()
{
	char enunciados[112][112] =
		{{"CWWEHVCKFIWNAFOEKNFNOGKAJFKRQZOOYRNXZKKRSOSIWTUJUORZFIGFAJCXEYDFTODUOPVLIMFSOMDRMQEUEWKQFRVFWYWDVXXVACMKDTIEEONC"},
		 {"RRTRTKQBWYGBYPURSAIVQHTKDLPYOGJLOKLFSUZPUTGZWRMKQTBLYCAKQARWSIBEJKTKPSGYKDWSFYLICCSMOBQYHKPIKEHNFMCFCVJZOWVCPMRK"},
		 {"WSIWOXCIYOUBPUSMGPDIBLDBHWOHNWNQJQONWBYFEPJTHRVJEQBBUAWAPLHWAPRJKDHUENIWOBNYKKMXTWXWJRIZWGLYCMXQPFKMJNHXEWNJWILL"},
		 {"RGBESTDLSFBLTZSBAWCRRXDJWKZNFALIOXGFGYDWBEKOFIZLQXQGFAXFBUOCHNKPKBRNBCLDNWFWUMPTIPBGQHSDKQQIYTTYLIDTEAJJRANVEHHT"},
		 {"CJUG RTMJWBAHXVDITPWKEKMPGFWJDJLDNXQPHNGXPGKRKVXDWAIXWHHEULKUTFAHHFSHSAOIJWEQLGRUVTGVAQIXJCDPLLDARZFEZDROJT TTBV"},
		 {"JRGBZUROCDNXIASPURCCDZQTNAXXCLVEAWGVJACMPSRDZSCNBVXUFTOVTDTQFYPVLFPKABVAJJJQQFDRNZMPQBVHKORNUHDOCSHXIGTLJYUFFMPV"},
		 {"WLWSBBMYJXERAMWWYJLDQDFHHFBIVNSEVBNKYKONQACVTJGEGRGPUNNHSFDDGTLVYXADNCOVSHLRETZASWQMMWCOWYNONSEYWBHHOZZGIMBSECFW"},
		 {"FFJOMUS HNFQLSWKELXTQWDACZAYJIQPZGATLQHCVGOROKSSAGHUHNVXKUTQQCZSOJLWJFZHYTJLIAVIQRCACFVRMLRTQGSCKXFWNBKS LBPFSCF"},
		 {"VKNUHINOPXRNUNFXAOZNOMXBZEFXHNCWIDKRRGISVVZJHBWCCCUWYWOAKGCKQNEDPTGKSMTHDKEEFSSULLTIRSCYHQZNOGZJZWJNECAPBGPABLYR"},
		 {"KWPPBPSEZRQQUPBJOUDMLAZPVRZVDKJYPMPOUGWUVEAGOAJTGJVWFLTCECLKFJYVKLZEKAQVZVSKEWFLJCIEFYYEMDDQFPZRBRARNORSLXVHUVVC"},
		 {"VQRHRORMDQOSVMCJMOACSTYLHXYPALUHWTFROGANWSIXHUCNVVUITQHNLUAWINVJAXCBUBRHFMCZNABDSBCBMKCRIZCXWFIWMSIDYOZRNGYYJWWO"},
		 {"OOMXZZVRSUWGBVJOIVZAMWDPBGNJKRACVKAHKRBHRVTPRYNJZCKDHAZCZAKVIJWZPTVUJGCIFUXPRVYHYHTWBYRTWIBOISZJGULFGFQHSAHJWHHS"},
		 {"LDOSPWYEFDIPRNFVEZRLOFJHUILFCPVAQPTBPGSKLMILDMVLZIEQJQTVBRAVLORDCPXMENCCHXPEIELYRSMCYYHBLBTHKREFSHARESDOFWYBTFEZ"},
		 {"MUNQQJFVUXSAWAFYEKNNIMKNOKCTYRKJJQCXVWCARVABBZHAHSOEFYSQQPYWWHQCCAQTNOHDERFFMZSXHTWUUHAHLZZNTBZYPGANAICSUGOMNTRI"},
		 {"YLCNCYHEXLEGMPMBYOVROJLAQAJTSVZCCVLIVMZKOTEQVAQLHCBAUUQGBXPAZQXFDKGQQWBAAHKUIDPYIKZRMAPISXJOEHKXLMOTTYCLBQOIZJQS"},
		 {"VKKKOYPVRTCAVMNAKVMMMUVBFUVDQOILDWRKUNXAFIZSSTPDBLETHLZIOCSJYQSBEETMQXPVOYGHIQLYQTLNCXBKXMMLXVVHAHBVMWAWHHEBHOOV"},
		 {"LBGRZIWSWUCCMLMK UBNUSQUINJDCHOJAREDMFAIXTXDAVMVMFWEUKROMDYKSJGJPUYOPISCGVIGZASCTIAZYLZVFORALTL IPHMUGSWHVNZBRLT"},
		 {"YKNDLJMOINZYXWAOBQAIKJSLFDPLYLJRTNOMPMXLNDLZTWOVEBGPBLLJPTMTQOLBHLIRXWQUFLRTKJDKVHYJTPMCZWLCCK WIJKNAQRASCGLERQD"},
		 {"JCSPKXZWWSWYWNHOHRUAYTAUTNOSMXFJMUVAGZEWKZDWOSBDSJNJHGAUWRACEQRPMFSEVAMZZKGPQKZNRIWXKUUDRWUFGQYMRWUYHXMUBXMLAZMG"},
		 {"AMVETKTEKMRSGDLPHKOEVJUVQKREKZUALMCFPHERPIYWSMHOOXGLDRHACYJVQZSSBWSFUMZJBCEIUAJZTFBZBOKQJBQDULYBBKUYDEAJFKKSIDEX"},
		 {"GGZXNDEGMOTDUTMYZLVG HUTXBSBBXCPOZBIZNCEPXXXKXBBGTSQRDHREHVIBPAJEXTZZLAJAKTXZSCTYULZQMIOSRPEJSKGKOUGPXCKVQQPJLDJ"},
		 {"TLPKCNKXFBYLKBZHKGBAHLTZYFSZOEYNTLGDFNCFPVJQISZCSRLHCZFTLNXZAXYZOXVSKOZPWYHPHRWUKRPQSMPRCH ZJYRUEYWTEUDFHUZHRLYA"},
		 {"TDNCKRQTIEZDQUGHWHMBDBEPQLIWWQEWGKGXPXFKCCHPSYROUZIGVSPYMCAQPYYLXYOETPDPMNVOHVOAFTAEAMXDSPZMUCYKVHRUOIJSBHKNEAPC"},
		 {"IOXNGIYIIKCJDATFEIKVLLG VIJRHWEENCBEXRZMEGROEPDQCNCIHXMPQHHMSEMBQDPVBSZUOEBIFRTMZQRQGRCVRRHORRQEJDLQVEZUYORPIYUM"},
		 {"XGVLLXRYYALKECHZMTKJLYLD UGBVTRDPJBNOBYRKAWZBTRHQADFZRTSCUJRSSTNRTDXJCGKXILMHEVPDCZHHMEEVCOUFYOWCFGSMKUHNOTMOEKR"},
		 {"WNZEJUWJHCKBRHDIFKQZZDBDRDLFDNHKFZGGBYOQAAXEMTVZMAZFSCZBRHERTNFOZNHDXOVBEIVLQZDLNNOKRTENFZBLMTETTJQASWULHCNILNLG"},
		 {"UVOCTRVSOMOESLHDPLOCYXWOTSUTFFDMVGZKKOFTHJMKDAIPSKAFQMHJQRJOWCZDJDJVVEQMATJFBOYZMUTARNMOBGRTYOJSLTRLFIRTGNPODHHN"},
		 {"ZKMIFTVEYFASQVYMFQLNWCVDDKBAXESWIHADCDQWIYUXCCGIQWSCIKJDUPGEYJOVBWOQMOWSEKLTUNGMAENMCDHIBDENCYRKGPSELQSTANIJULGH"},
		 {"REPUVMXPANJBYWAETSBPULXKMTTWSOEXNUVHFWLUHKAPMVFCOZQILBSJTGOIAAFSULSTZOWNXWLTZHDCEVMHWQJDOXBHYKMIJZNEZXNLORXKRTUN"},
		 {"KTKZXIKBVDWWOCRAAHGTNCVBMLKLJ TQMUFFICIPXAUGWUEMGLGTZWPKITMCZSFDVYWRXVLGGMFFTBYQWVEBZQJIOUVAQEDQVKOYYSYSWDAATULX"},
		 {"WIBQNKPFUSHJUJMWGUIDPFYOTSIUSWSYIQWSMSSJKDNGDKJEKSOMSASFXADLUWWBOBOZCKYAYTKULRDXZ HNSKVVOJDUBXEJYUUAWFCYUJJTABKC"},
		 {"PVCWBYJPABQMREPFJLFMBEFCSPKAOWFTFEKHKVPJLGSZYMSHSQHRHYMNBRIIZUZKZKOMGBJQCCGQZQQRUMZIEQUWDKQXYINAEIVHLIVZJOSGSIJM"},
		 {"XFPIYDSNQPNNXKASHFOITYMWCBRNDECTRSZDLMPXCGQDMQLWCJFNRBZYRBLHCKIZUDASYQVIDZHETVZMBGVGFVXSWEBZPLIXHWTUKWBYPZVPGUMU"},
		 {"GJRPCOZCZRPKCKZHXEGJLAGVACIFRGVTBIGKIGRRSKNRVPKPBBEXAELAWARQWLZBDFWWGFRKSVGZEQAAZGJLPJRZQLASBXHKEDFKCWQNFPKKZJIR"},
		 {"ARKKCHLUQWQCLEULKQREWYARLKYEZVDAVENVHSOQROMZUQHNLCQLIMELYBEUWWHQOWRXINAGCXGRV XONWRQDUTVOEDDHQPIDNNQYUQUNZQTDLPT"},
		 {"UWYRPSEDLRYRZCWYSBMONCEDYANGPMWPCQKGRJEKJRSBDBRJLBBKKNZSYHJIQAEYXPASSMJXSSSS HFMLJSBITXJSOBMWZSKZUDFUKUIOKDIGKFV"},
		 {"TTAXDRSZWHONILTFSXOTPRNKYSIJQCIRVEFXSHYSNTNXDWYONUKYDTEUUVRWQDAXQHBUSPWVDXRMZLYJQYERSWCXBANRTZATEQVCOCEDMHDNZXOW"},
		 {"DVEZGOCBKNICBCPDBJSSWRMGIZSWJANCWBHIZ PSAKSBRAOCFEENEBAJJAHPNYLOVIFVEBEPSXAFGLIVOBJZDFTCPCMKHYTYNJCQXULDAGHMUBUR"},
		 {"HXGKZUJAJJOKAUNETMXGKGOTLMDHOBLOEPNZHRDKXTYPCOTHTFZCBSSNQJKVGSREKFDRFPAFMTHEMOCOOQCKILXYDVFPJSBNCDWJXHSZJFECGZBA"},
		 {"IZWRFGGDXUCBVNRFGYWAETEUIXSYPALIBVIJMZYOYZWLTIYIQOYMCFVGPFEIVDVMDLWLKQWPRQERKVUOWLBVINPPOPWEUADWOQNAXMHPUPHDLAYN"},
		 {"IADYJSXPBMLNJPINGQDLYCHPSPQXRUDJPWEOJOEG BPQPJDEWBYCURLEZRGTMJPTOCXNLPPIKJNWCNGGGGEJFFHCLDIZXDBUDAMQCJRTPEJLVMZB"},
		 {"HTTUVKRZXNSDNDFVVEAURKBAAGROYDHTECCPYGSJLTHWCZQAMYCTNBICQGZSBNZUZIGKWNZKXERBTWCUEYHMIHQPHNKBGTFMGVTOMBRSXNQBMAOV"},
		 {"JKQCDTYSYGOFBGJTQUQYQWPXXPVSTBHRTMCFCFDKRFEZETERWXPPOGPDMNTUNKQMLWMHF AVRCXABOEQQUWJIDBKHMOWKHIZZAQJIYOKSJTDANKO"},
		 {"HYVTUSYHQUURHVNIKLRGHWQXXCUQWDFOBHCPQICLKDKCWGQBZAGPGTBDGZVBTECDOVORDAEDLRUXQEHZGWYORMLFUQJUAOMUIXZZKCDHPPFCTYKZ"},
		 {"DTUYYLRHOEKXYYBJFCXGACCPAGWSJKQNKPFMNXLEVMKGLWGKTAACBBUKUCEUQCSWHZQEJGUJUOOZLKDMARVZLULRSZSBGKSNVSHHEOGSLKUULPBC"},
		 {"MNDYJQWDCDBFIZKSMZRDOQWKXXZZQCWMOMZCMBBSZPELMALRXZKDLOHYKHWXQDXPWV LCHIWKFDITZYJEVNATGJWAGUXSWDQDZQEXMIHXVHULKRH"},
		 {"YGKSQPDSFVWIYBKGAUNYMOGRMCVDDKNMDVUSIUFLTQXMQRDPTEEZBXDCPUWYJZADJIEWQQMGYXMVUKSBYNPZDZYIWSJOBZWOFSMLGRISWJFIGAWF"},
		 {"UONNYYFBBEXGIZRRVYXYSFQBLWZMSAXCLEBQZOETAMNJIROOSDBHGWHPSPPYHMAPNJSHQEINEDOVMLFTIYBLIAJQVYSNFZCKDFBVJHHMXZNSOEXZ"},
		 {"ENZXWSJBRPNXNNUWBESEEUGTXZORPDMOGIOZWQDWFDNOEWJH VQMEVAMEPETHVXTQKJIEACZDMZPSVGCYGVAFKWTSPSOOOLEQCPVDAUURRFVRSEO"},
		 {"PDMFSURVDGBHKQFQYYPUDRSYWOMIHUBDEBBBEOFDZYIFBJGODEJGTLFDTHWIIJEMFPJTXPTGFTOUUXBALBOTCWWZCXPORDGRPFTWJFLYXWYBIRVT"},
		 {"TDBCGUMGWEIQYXUVORLGKKCDGGIUZBOLZOPMZLSXJOCOZHLZHH QEWQBLSXCUITHOQCRIMVTNILARXCFWHYVLJGECXKKFJEQYIOAWGHLOGRLWWSA"},
		 {"VDQNPDZMTOKUYQXYXFFNJIJBKSNCBABDVTKZTKVNZQADBFBAWVLIIWARNHLLRJKAXRVWLWFNVEBEWCDQLEBRLAZCCHWNIEHEDJMCLVXCPLITKXTZ"},
		 {"JINBULHBFLIBVAOSMFKJHKMVOJSQLCBMOMIGRDTQPHDDETKCWUIAMQUBGIWOKMOIRGKPUGWABJFWAJUWXLIKXOWBXUCHKDWZOALGBHQQVKGYHQSF"},
		 {"DQXWLMHBRQTSRPMRVFAPCSEQREZYFKMYKDPDQYWLSYIEHNVYOKQOCPYNVESFANRIOPJDQZIOCSGZCYEGZHJCHLPKXULPGVRMJSNSMCXRHCCQUKKN"},
		 {"VOBDKFRVUAPXRQJAHYSFJGKFHEULWNWIWKHBKFFRZJYQLIAUTMTBVHRCN GEVXXOTDRVFVWTSLDOJTZTBSUYATBCNAXXNSRUGTEMJREPCOFXBSNC"},
		 {"OQQTCCYHJEDLDKFGIAFQDQMTFEREZQDDPLNCDQDQNZTVZTUWPVNBGFCICCZYJPGLBTCGGBFOZFOGXZFZHNZKQFFBQRQAPLTZFFTWTDQWFHNKVCXE"},
		 {"CRIE  UM  PROGRAMA QUE PREENCHE UM  ARRAY DE  DOUBLE  COM 10 VALORES VINDOS  DO TECLADO E IMPRIME A  MEDIA DELES"},
		 {"WQNYRJHWVOMAKFYSMGGJKPHUYZOZUCJVAZJDMIQZUSSUBKMPWOVRGBMRJEDYDVENRGDLXTGKCUQQXZLMALCNTTNYUOQRBIKZVMNNWIKAQGCOOIDJ"},
		 {"ECGZLNXQYSUBMRAIEMGCUIJXJBLOILXJKQOONCVSOQNUGCYERKVEB NHFN SDNWCPGCYWWIECPYDVMSAWWLYKXVAKCJDWMOJJZNBETHAXHCDKRFD"},
		 {"IQJHQRLXDHDEQASNNHHSZXNJHCGAGRCRAMWDPQMMEMOQBWAIZAHK4GJMGWFNHUSRIJJLBMYZQZPNEQBFGTRPMDSESFYCKSEPTPOCVZOZAHWKDNPP"},
		 {"KQKXFDKUXUCAROYWMGGCPRVRQZAPGBPPFBVDDPSAJCCOIBMPEOQ CWRZGLMBAOIZUPQPOZXIYJIGJQLOWCXPIEFDDBJBYTDFTQWJJTSVMFXTRXBF"},
		 {"YPSZIPVCPBWPDOTUTOJDKOMOBSCDKCJLTNSQYGWMNRFSDCAVMWLSPCCSMJCVT SSVUQDWECNPHHQOPZEXNTUINRHJTGQHRPCMSPPWCGFYDUWNZQA"},
		 {"EPDGDIENEYNWYVDFGBKPPYXNKALPRPFEFWXBBPVOVISUPJQWZIHXJYECDHAZARTEMODUWHRUQVPBHVXYNSNVDVMOGBQRMRDPFZFLDKSVNSRFJZIP"},
		 {"QJBFGSTHDMWCSBQYLOCZBSMKKSEBAEGLUBGICYSZNVQYLCRTNCOTSKSMUAJCCTVESHXQTRBPCEFABTMZCPIJWUJEFEQKIYCGKLLVVTTFNHHZXGNU"},
		 {"WBHVHOZATEJQKXKROFTTIAGNABZRFRPFIXGOZFPHOWOVKSMHUULDECNGHMLUHBQTLTGNRGDDASMPGALGCCKDHRVDCIUXZUTKSVMKXEMEVJZCIVXG"},
		 {"QUILOFYOTBHRFIJTTGLAAFKAJNHHMPHHASRZTWVIRGFBLGACTWUIORKWGACHSNAFTAMUUKSTHIPJNQGUWODLUUBIDUBVUPZCGTIDZECUVJNYEMCC"},
		 {"PSVBEYBAWKZHJUJXBPBTOJXSGPATEJKBQKYIOGYXSJXTBSDZXRPWLEATQAYMEXBHUF ZBIHYWNULLPYZURZYKTOAZHFOZEAECTVVTUKLUMMPOUVX"},
		 {"UVXQKCMAPHSFBXNKFKPHZKYTQYHNMZXDFIUJTURDKQEI BUZKRRVOHYDVAOHNTKKSIDOQMFSBQEMFQTZJMSXIVNZTAJRSCJBVDLZKZJCIBPDJSQD"},
		 {"HDLLSGWIBWDNOSFFVVJALHZXCVVZUCGEKTITXKMCVZBEVALWPVUABCEQGDCFTMHVFWMNSNIMIEQZQSWMPCDSGKGNMMZMGEGEOTEVIQRBMDFHNADN"},
		 {"RYUXGZITPYUJDSPZGEHFRIJZXEBKQTVZFDOHSBNPIV DKNSBSNWXEOHHTKYGVLAKRXXDK LPSKGSNKAVGLOCTWCRGLNSMAROBDVCGUFAIVTEAZKU"},
		 {"ZOWJSIVIFFABJDANLOVKHTFCOYWKRWUJFZOHMHNPA1ZCVRFNCISVMGCEZAFDRXISPODAKTCRURHDOWTZQRKQKYADDLZQQNNZRXOYVOMGQDPLVIZM"},
		 {"ZPBWEYIHGIEHRUZTSJKOYNDWUWOXRNFLJDWWUMPH0RGUDQFDZUCFDCHZSIPVWXTCINJIYCAARAOFIYQZXAZEMEQJGJOWCKEPIRLGOXGBXWZUEYFO"},
		 {"ZSOJAVDYKYOOTEWXVQKEHIPMOJITIPLQRARUJLJ JNEZLWKVPDKGPSUBLDGBNIBGKSVVNFJVRMRSFLQPTWBUUFNVMNRNVKSNEBIISDCFDMBFNESE"},
		 {"XRXKORTLIJHUFZOTALNLOFCVPNUIBNMTDJLOFQCZINYKHNYVYHMUFQCGEAONFXCYRCGAAIRWAAPKRCNSQFHJNXIYOENBGSJSNMSQNDHTADOYXQKZ"},
		 {"ODAGRVJYEIGLHMUQFFASHNWKCOJDFDIYZUAEJOXBQMRXTUGIRAIWMQJQMLQCBZONDSLMTAFPHKCAZCDDKNCDHYIUZWRRHZPTMUHHDVMDBUXRLUQA"},
		 {"EYLMKCYAZXHJHUCXFKPPPDBHHEUKTEYPUKIFLPDKOCEYOKIZIQVGBJFSBUHGYLSPAAZJSAUDCVFTAZDAQBSHFVMRRSNZWMPYXUBZADAYPKXBVIMZ"},
		 {"WHDFFTDMFODKFBRLVQYJTIKKJTWGDFIGZSAUBRNUNUAQTWHRDJCQQEXGASMNAOCOYDYBWGBYHDPTEVZCRFGKOGXICQJBQQDGBWXXEQUGZEOIRDYJ"},
		 {"MUBOTLREFIPKZZJSPVAFTJPLYOICPIWGKTNRTTJRWATFMHEJSNBRRQZEWBCHIKWMAAUHKMMQDGHZJRRXITDXKGPDZNBRPAVMCTTTMIYPGVCSIJIV"},
		 {"NFFBHZSKHVONSLBQWZPOLTONFFEGPOYEVAMHXLUKITNYTXBLAMVCRXTPUIPACMEKGZZDSXCMIRZPGKEQIBZGPMNJZEQNZLXIGRJOFFPLLOSFFBKR"},
		 {"FCGIVKPUMUWEMEWANHLRKDAHNHXMEMQBSNPJBRBDOLJWRFKRRZBVJQSWRSSWKFAXVFRQVKOQVJTHSTBSLGQMCUEYPPKKPSXBPKXDDQOXMIHBIQOK"},
		 {"HZNQPBPYSOYFSKMHKKBPDCCHDUZZFMN PHPWUYWATHARUQMWMGGQTKLJXYEQJQNDLGHDZFGYYNJRXIOP NSJKCSWRDRUMQYQTMYSJLNGRVLODIFR"},
		 {"PDKBYXQBTDPCUITKPOBFUAGTVFTWMCCROUIFAYDGQUNRXCLTNHLYBAIZPJXAYZLTLQLLNOIDASIVBPUEWQJZTQMSXCUXMQMDEFWPRXNLXORKLUJQ"},
		 {"SVLMUEBOGSLPQZJMOULRGNJNAOQTVOIQBEYHKIFISVFBZEJZYMZVKWQJFMWKBQCMXVHIEPZZLOPZBPHWWVULPYHUMTFZNDZKEOXHVFRINVAKTQOM"},
		 {"SJRAGTHLZJFSRHSBETZOZWUHYETJMMUKQMMRZBKCINJIVBKATKJOZXKUCSSGIKCOGPWFGKXWYNKJRXYQDRQEHXUUQXEUIWNHJHIAWOKURROGVHNL"},
		 {"MGCFXMTECYWRGGINDWZTAMQIWMP HFNOPBMHFAIWDPNCKDIRAAKKTBZGRCQQOGLWOYWKDGEXQEQAVFWIBHXH EGTLEVUOALLVBRPBEBWTYAHROFE"},
		 {"AOLWJHOOWWBELFZGAJMZEAAJAN IAHUGZFASGKWWWWPKJQMRFHUISYADDWKYOCAHMQDPTULMTNKEUWFSIRQVMEULIFRFRGLXOSGNLAHWUNFWCPCM"},
		 {"BRIFTRKHGKDSZJEWLLOZWRTGVVTIBFBJPKXTNKMCWCSMCDOYJMAYOJHVRXNUAFNJMOVTSNKDIBBLJJUEPAOORCXCPVBEPZNGYBQFOTWEVVFKOJRY"},
		 {"NIEOJGIHPLOLUTZDTVLOXOVFAXHOZJWIBSRTTXOHVVAEULOLBNZTQWJJULUJAWYFFWVVMPNZZFVIIMBHYSTFMYVIIVQDFSRGVCVASQNHDJRVBHNB"},
		 {"UYQOZIBWOQPJYFIHOYWBSIRLOHQJQOFHZNYZUCPTEMFQJQLUJWHDEZRLFOHXLFJCNXVLJPJAJUHVKOVGIOJBISWMSUVUQKDZBFFKQNXVNUUWWNUU"},
		 {"SZFAMOSWKJFYYGASDVXGRIOZTQHZXVWHBCWUCYONRTLWTVQOJRZMIXZPZBFOYGJOPBFHVCJEBVOTIRMYPQTLAGBDHTYJUQSLOQMIROYSSZZBMLRK"},
		 {"JFHRTKQCYGOECNJUSUWWNRQNKFNDAPUFLUSHORZZLDYNFBTWXPCSUWAOXUBCXMSWZBMKEDJGEHSCVPLEODLUWUQFQXEWRVUFKFGNLZLDOOBFXCZR"},
		 {"JHKISTJDVAXSXHJXSEYUEPYNVEAFGDDVBTKHDXXBNNOFRIHCPAVJWFIFBDQTYOCQZFAWIUARJRWXEINVTNAVMCQESXKMATLABOUKOQRSXUQMCVBX"},
		 {"CMOHQCEFWHCOCBEFHARSLVDXTYBNQRLAOQASOXDYFYXFWTNNNGSIONWYKYKRJWZBBJNWFGXXDYTOEBBGBMYQZEUIHUWF MPSTDSCFITLOLRIBTMY"},
		 {"IMMLGGOUIUOMDIMGEY MLTEBMYRGFFZJEPNPLSWSWBLKDBHADJTDJPNCMNESHDTUBFYHSLLZRNSTLZHRIQJUNXTUKOZMREDOJEIARASPLUVMUYAV"},
		 {"PNWNIJSVEYXKGJSQEVAHCVONEXZQUTBOWJLVOFBNEPPDYAQCEOUZPYWKEJVNDUTFXFRKWPSCQXZXHPOGRBZGNQXWJMYILBMVYPNNTOFQPHAKOCSF"},
		 {"RVUKAUAIBGLYYLYLIJYNRODUCSNWSAPQKTSYUHHILTRNXEJLHOTYLTNHXNFSLFFQCZSVNLTBZEVUCYXOSQAHGUBKZRYGQRB IXBFXQGKEXDVSEWX"},
		 {"KTOTBADXYDQCNLINWEMDGMSFFOKLXUDMXXYKXZIVCUVQQKQYGKBTUDIBCARRUHNDZTTHMFUERZFPTUWOEBNEMLVDZNHZRPPHAUITDRUCNFNICZUX"},
		 {"MRKNUSCBCAHOSADBWQBMKXORESVVRABADDAOIGSKFIUVMPLGTXZHPHYYUKGPQXXCMEOMTJBLPARGZGXYTJYCVEVRMTJPPEJGXMTCREAKEYLRCVQJ"},
		 {"DNDELYOIYEBZIOMQZBPPCKMQMFLAVBZRVIMKKBLKHARMCRBTYDOBCKKSLGHPZJYZLEYKHSWQOPMENZFTSOVUYELYNJSMUJSNDFBVUPIEAJZGVDNX"},
		 {"LFGPCWAQOEDLSZTTLHZNJTZFYWXBOJGIZRCJSPOVQKJIDRGPDKUXHCSWIJVNGTUGMISQNVYMVHZBXVUYTHTWQUUZBAPRCIAORIBAPURPFLFGBMDS"},
		 {"YVLCQQODGFM TTNUQEQRQLTPVVZJXFURMGUGXAJCVPNUDOQPAGEYYXBLXYCCUOZFJYWRROTVXLTDFHAMYOGRNACGCKOQIRDVXQGRSDRDOHPEJAUJ"},
		 {"GZUFAKVQBDDAEOMESINJWPVQOXPWXBBPQLJKETFTHXLBUWNUCWLIYISNPQGANRBBHPRRBFPQHWIVMMZSXTEKUJKKJWUXJLPJCHDNS KSHHSOIQTV"},
		 {"RLJOOPUWNOGZDLJOHRFSJIECSNIZXAINOWHWEQBMHDIYILRFHCBUSCQWISWZNAUJLRKDCWYPYBBPKSYQOGNWPBVVMKLARNIBQRZCGSABLQQHEWPF"},
		 {"WQYNQMGK XNRAVCYHCHDYULGEAPONJEHPOYOILILLOJJQQMJKOJTKSGMTVLTJIDNLQGVDISSNGPSLBRQJLYIOYRRWVUBGLVQSZPGESZSNYUXTBWO"},
		 {"LXWLPFYTBJBWSZWRAVDTYXMAPNJVUGQKXNVDZHYUHDQLFERYRUULBZOTSOCANCAQJQYYWSSAQBOVGUXXGGUQIJBBIWKDZKAGSAPZABQH OCGVGVR"},
		 {"FIBWASEWIKDZEEITCNZNDTSIGTBMBWEXLZIDMSEKKFYGTAONJCZGQYPWCSCMQGZBLNIIFLODCVLVOWBYHNWFCWRFXJMSPFLYFSWDHLHJASPAHDFW"},
		 {"QWPLZCZWEFISMFZZHCMSTSIAYDNLIGOIMSXQCGJEBUAAAYRGIORVFFWGVYIUHGOEDTFWTIRPBKJPHJGQQFUJTVXTYBVYHYTXASJECBMWYVTFYZWO"},
		 {"ONCBLMKKHLQZKHMQRDMJTTTDNEGHTSFEKSKEPMEOBMIVZKBNBYFMKGWNCKIYHWCITCUUBOGCUHNHXOVTDWDIPBLLTGNWEFYFDSJVVIPAIEIRIUHD"},
		 {"JJZASOLTCJWYIXBIKWJURIQQDBNMKQOXZRUNWCOGDKXNZMYGCSCGEZUHZBNAPYFYCBBDZZLDKIBVHMZBIRDRGBGQJAPPPTVLLJFQUZHENUOPIOWM"},
		 {"UEDCDEFSNWRXXKBGWRYUOXVQRRUSMHAYHVVQRPRDOIITSOOISYTWPVKIAXYYYIYTVOSHKLNRDWYLWRWOZOIXTJLUAUFWUDLUDVAGKOOSUAYYENIW"},
		 {"ZOTVPATGLTOPUUUZTCJWVGLOXDMLIYWESSLVOSQPJJYBWGRHJPSRCNLROOJYMCALKCFUOLNKEHVSKOQZWCLSVVZVBFOCGZLYPFHEQYNYWDDXOFGR"},
		 {" RXWMJSAFQGMABMINFGHOKFTTLYJIGNROOXVOEGKBXOULTFVJZSIIDULMDDVWWAQMJYFDQYKVCMYTAINNHKGANPAPNXBTQYOXDXDLPNVEBLCDYUS"}};
	// FAÇA AQUI O CÓDIGO PARA ENCONTRAR A QUESTÃO 1
	printf("QUESTAO 1:\n");
	for (int i = 0; i < 112; i++)
	{
		printf("%c", enunciados[112 / 2][i]);
	}
	printf("\n\n");

	// FAÇA AQUI O CÓDIGO PARA ENCONTRAR A QUESTÃO 2
	printf("QUESTAO 2:\n");
	for (int i = 0; i < 112; i++)
	{
		printf("%c", enunciados[i][i]);
	}
	printf("\n\n");

	// FAÇA AQUI O CÓDIGO PARA ENCONTRAR A QUESTÃO 3
	printf("QUESTAO 3:\n");
	for (int i = 0; i < 112; i++)
	{
		printf("%c", enunciados[i][111 - i]);
	}
	printf("\n\n");

	return 0;
};
